#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 6.0.1
#  in conjunction with Tcl version 8.6
#    Apr 08, 2021 04:35:28 PM +07  platform: Windows NT
#    Apr 08, 2021 09:09:37 PM +07  platform: Windows NT

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

def set_Tk_var():
    global che49
    che49 = tk.IntVar()
    global che50
    che50 = tk.IntVar()
    global che51
    che51 = tk.IntVar()
    global nama_pemilik
    nama_pemilik = tk.StringVar()
    global radio
    radio = tk.StringVar(None, "Matic")

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

if __name__ == '__main__':
    import bengkel
    bengkel.vp_start_gui()





